# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37ea5d85d9b14efc1a764ed34e91d6d9331bcda006ac025a2ad1eefb2064668598a422b7adb2b7141858695b520957f4f676b72b486faf1ede57cb9c823f472f

test:
  secret_key_base: bac8c2df8b18d9ed5548f01ee76980ad4c56ebd125d758ef175c9bcaaffd4bc5cdb3a860cb5e33d52629cf2218f4c6f5fd9d60f8fc8f1889d1e6c801c7d3e045

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
